#define error       HSV 20 0.5 0.5
#define blue        #3047ba
#define green       #00ff00
#define red	    #ff0000

#define blue0       #000036
#define blue1       #114BD3
#define blue2       #116CD3
#define blue3       #03022B
#define blue7       #6284ff

#define brown1      #161414

#define grey0       #000000
#define grey1       #101010
#define grey2       #151515
#define grey3       #181818
#define grey4       #202020
#define grey5       #404040
#define grey6       #505050
#define grey7       #909090
#define grey8       #a0a0a0
#define grey9       #ffffff

#define red1        #2e2525
#define red2        #4e3e38
#define red9        #ff0000

#define yellow0     #c4b8a0
#define yellow1     #6A5148

#define main_text   #c0c0c0
#define main_sep    #2e2525
#define main_hi     #c0c0c0
#define dim_hi      #606060
#define main_hilite #4c2513
#define main_lo     #000000
